title: I Bet That You Look Good On The Dancefloor
tagline: "2000s Parties at El Cid"
description: "Photo blog of 2000s dance parties at El Cid in Los Angeles. Flash photos, flyers, and galleries from Look Good Party."
url: "https://lookgoodparty.com"
baseurl: ""
lang: en
locale: en_US

permalink: /:categories/:year/:month/:day/:title/
markdown: kramdown
timezone: America/Los_Angeles

author:
  name: Look Good Party
  url: https://www.instagram.com/lookgood.party/

logo: "/img/dancefloor header 4.jpg"

social:
  name: Look Good Party
  links:
    - https://www.instagram.com/lookgood.party/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

collections:
  guestbook:
    output: false
